'use client';

import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';
import { Language } from '@/types';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Simple translation object - in a real app, you'd use i18next
const translations = {
  en: {
    'app.name': 'KheetiiBazaar',
    'app.tagline': 'Connecting Farmers and Buyers',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.role': 'Role',
    'auth.farmer': 'Farmer',
    'auth.buyer': 'Buyer',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.changePassword': 'Change Password',
    'auth.currentPassword': 'Current Password',
    'auth.newPassword': 'New Password',
    'auth.confirmPassword': 'Confirm Password',
    'products.title': 'Products',
    'products.search': 'Search Products',
    'products.categories': 'Categories',
    'products.filters': 'Filters',
    'products.price': 'Price',
    'products.freshness': 'Freshness',
    'products.rating': 'Rating',
    'products.quantity': 'Quantity',
    'products.unit': 'Unit',
    'products.addToCart': 'Add to Cart',
    'products.buyNow': 'Buy Now',
    'products.viewDetails': 'View Details',
    'orders.title': 'Orders',
    'orders.myOrders': 'My Orders',
    'orders.orderNumber': 'Order Number',
    'orders.status': 'Status',
    'orders.total': 'Total',
    'orders.date': 'Date',
    'orders.actions': 'Actions',
    'orders.cancel': 'Cancel',
    'orders.track': 'Track',
    'orders.view': 'View',
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.stats': 'Statistics',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.recentProducts': 'Recent Products',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.print': 'Print',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.undo': 'Undo',
    'common.redo': 'Redo',
    'common.refresh': 'Refresh',
    'common.reload': 'Reload',
    'common.home': 'Home',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.help': 'Help',
    'common.settings': 'Settings',
    'common.profile': 'Profile',
    'common.account': 'Account',
    'common.notifications': 'Notifications',
    'common.messages': 'Messages',
    'common.inbox': 'Inbox',
    'common.sent': 'Sent',
    'common.drafts': 'Drafts',
    'common.trash': 'Trash',
    'common.archive': 'Archive',
    'common.favorites': 'Favorites',
    'common.bookmarks': 'Bookmarks',
    'common.history': 'History',
    'common.recent': 'Recent',
    'common.trending': 'Trending',
    'common.popular': 'Popular',
    'common.featured': 'Featured',
    'common.new': 'New',
    'common.hot': 'Hot',
    'common.best': 'Best',
    'common.top': 'Top',
    'common.latest': 'Latest',
    'common.oldest': 'Oldest',
    'common.ascending': 'Ascending',
    'common.descending': 'Descending',
    'common.sortBy': 'Sort By',
    'common.sortOrder': 'Sort Order',
    'common.page': 'Page',
    'common.of': 'of',
    'common.results': 'results',
    'common.noResults': 'No results found',
    'common.tryAgain': 'Try again',
    'common.somethingWentWrong': 'Something went wrong',
    'common.pleaseTryAgain': 'Please try again',
    'common.thankYou': 'Thank you',
    'common.welcome': 'Welcome',
    'common.goodbye': 'Goodbye',
    'common.hello': 'Hello',
    'common.hi': 'Hi',
    'common.bye': 'Bye',
    'common.seeYou': 'See you',
    'common.takeCare': 'Take care',
    'common.haveAGoodDay': 'Have a good day',
    'common.haveAGoodNight': 'Have a good night',
    'common.goodMorning': 'Good morning',
    'common.goodAfternoon': 'Good afternoon',
    'common.goodEvening': 'Good evening',
    'common.goodNight': 'Good night',
  },
  hi: {
    'app.name': 'खीती बाजार',
    'app.tagline': 'किसानों और खरीदारों को जोड़ना',
    'auth.login': 'लॉगिन',
    'auth.register': 'रजिस्टर',
    'auth.logout': 'लॉगआउट',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.firstName': 'पहला नाम',
    'auth.lastName': 'अंतिम नाम',
    'auth.role': 'भूमिका',
    'auth.farmer': 'किसान',
    'auth.buyer': 'खरीदार',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.resetPassword': 'पासवर्ड रीसेट करें',
    'auth.changePassword': 'पासवर्ड बदलें',
    'auth.currentPassword': 'वर्तमान पासवर्ड',
    'auth.newPassword': 'नया पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'products.title': 'उत्पाद',
    'products.search': 'उत्पाद खोजें',
    'products.categories': 'श्रेणियां',
    'products.filters': 'फिल्टर',
    'products.price': 'कीमत',
    'products.freshness': 'ताजगी',
    'products.rating': 'रेटिंग',
    'products.quantity': 'मात्रा',
    'products.unit': 'इकाई',
    'products.addToCart': 'कार्ट में जोड़ें',
    'products.buyNow': 'अभी खरीदें',
    'products.viewDetails': 'विवरण देखें',
    'orders.title': 'ऑर्डर',
    'orders.myOrders': 'मेरे ऑर्डर',
    'orders.orderNumber': 'ऑर्डर नंबर',
    'orders.status': 'स्थिति',
    'orders.total': 'कुल',
    'orders.date': 'तारीख',
    'orders.actions': 'कार्य',
    'orders.cancel': 'रद्द करें',
    'orders.track': 'ट्रैक करें',
    'orders.view': 'देखें',
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.overview': 'अवलोकन',
    'dashboard.stats': 'आंकड़े',
    'dashboard.recentOrders': 'हाल के ऑर्डर',
    'dashboard.recentProducts': 'हाल के उत्पाद',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.add': 'जोड़ें',
    'common.search': 'खोजें',
    'common.filter': 'फिल्टर',
    'common.clear': 'साफ करें',
    'common.submit': 'जमा करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.close': 'बंद करें',
    'common.open': 'खोलें',
    'common.yes': 'हां',
    'common.no': 'नहीं',
    'common.confirm': 'पुष्टि करें',
    'common.required': 'आवश्यक',
    'common.optional': 'वैकल्पिक',
    'common.all': 'सभी',
    'common.none': 'कोई नहीं',
    'common.select': 'चुनें',
    'common.upload': 'अपलोड करें',
    'common.download': 'डाउनलोड करें',
    'common.print': 'प्रिंट करें',
    'common.share': 'साझा करें',
    'common.copy': 'कॉपी करें',
    'common.paste': 'पेस्ट करें',
    'common.cut': 'कट करें',
    'common.undo': 'पूर्ववत करें',
    'common.redo': 'फिर से करें',
    'common.refresh': 'रिफ्रेश करें',
    'common.reload': 'रीलोड करें',
    'common.home': 'होम',
    'common.about': 'के बारे में',
    'common.contact': 'संपर्क',
    'common.help': 'मदद',
    'common.settings': 'सेटिंग्स',
    'common.profile': 'प्रोफाइल',
    'common.account': 'खाता',
    'common.notifications': 'सूचनाएं',
    'common.messages': 'संदेश',
    'common.inbox': 'इनबॉक्स',
    'common.sent': 'भेजे गए',
    'common.drafts': 'ड्राफ्ट',
    'common.trash': 'ट्रैश',
    'common.archive': 'आर्काइव',
    'common.favorites': 'पसंदीदा',
    'common.bookmarks': 'बुकमार्क',
    'common.history': 'इतिहास',
    'common.recent': 'हाल के',
    'common.trending': 'ट्रेंडिंग',
    'common.popular': 'लोकप्रिय',
    'common.featured': 'फीचर्ड',
    'common.new': 'नया',
    'common.hot': 'हॉट',
    'common.best': 'सबसे अच्छा',
    'common.top': 'टॉप',
    'common.latest': 'नवीनतम',
    'common.oldest': 'सबसे पुराना',
    'common.ascending': 'आरोही',
    'common.descending': 'अवरोही',
    'common.sortBy': 'क्रमबद्ध करें',
    'common.sortOrder': 'क्रम',
    'common.page': 'पृष्ठ',
    'common.of': 'का',
    'common.results': 'परिणाम',
    'common.noResults': 'कोई परिणाम नहीं मिला',
    'common.tryAgain': 'फिर से कोशिश करें',
    'common.somethingWentWrong': 'कुछ गलत हुआ',
    'common.pleaseTryAgain': 'कृपया फिर से कोशिश करें',
    'common.thankYou': 'धन्यवाद',
    'common.welcome': 'स्वागत है',
    'common.goodbye': 'अलविदा',
    'common.hello': 'नमस्ते',
    'common.hi': 'हाय',
    'common.bye': 'बाय',
    'common.seeYou': 'फिर मिलते हैं',
    'common.takeCare': 'अपना ख्याल रखें',
    'common.haveAGoodDay': 'आपका दिन शुभ हो',
    'common.haveAGoodNight': 'आपकी रात शुभ हो',
    'common.goodMorning': 'सुप्रभात',
    'common.goodAfternoon': 'नमस्कार',
    'common.goodEvening': 'शुभ संध्या',
    'common.goodNight': 'शुभ रात्रि',
  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Check for saved language preference or primary to 'en'
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage) {
      setLanguageState(savedLanguage);
    }
  }, []);

  useEffect(() => {
    // Save language preference
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
  };

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
